name: Deploy ERD to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Start PostgreSQL container
        run: |
          docker run -d \
            --name postgres-erd \
            -e POSTGRES_PASSWORD=pass \
            -p 15432:5432 \
            postgres:15-alpine
          
          # Wait for PostgreSQL to be ready
          echo "Waiting for PostgreSQL to be ready..."
          for i in {1..30}; do
            if docker exec postgres-erd pg_isready -U postgres >/dev/null 2>&1; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo -n "."
            sleep 1
          done

      - name: Load schema and dump
        run: |
          # Load schema
          docker exec -i postgres-erd psql -U postgres -d postgres < init.sql
          
          # Dump schema
          docker exec postgres-erd pg_dump --schema-only --file=/tmp/dump.sql postgresql://postgres:pass@localhost:5432/postgres
          docker cp postgres-erd:/tmp/dump.sql ./dump.sql

      - name: Generate ERD with liam-erd
        run: |
          npx @liam-hq/cli erd build --input dump.sql --format postgres

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Cleanup
        if: always()
        run: |
          docker stop postgres-erd || true
          docker rm postgres-erd || true

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4